server:
  port: 18081

spring:
  application:
    name: 'fairy-music'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://10.13.144.102:3306/fairy_music"
    username: "root"
    password: "root"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 600000

logging:
  level:
    root: info
  file:
    path: "logs"


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false
