app:
  api:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-app
      tag: 1.0.0
    resources:
      cpu: "2"
      memory: "1024Mi"
    port: 18081

  ui:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-ui
      tag: 1.0.0
    resources:
      cpu: "2"
      memory: "256Mi"
    port: 80

env:
  - name: LOG_LEVEL
    value: info
