app:
  service:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-service
      tag: 1.0.0
    resources:
      cpu: 200m
      memory: 1024Mi
    port: 18081

  ui:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-ui
      tag: 1.0.0
    resources:
      cpu: 100m
      memory: 256Mi
    
env:
  - name: LOG_LEVEL
    value: info

ingress:
  enabled: false

service:
  type: ClusterIP
