---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "fairy-music.name" . }}-api-deployment
  labels:
{{ include "fairy-music.labels" .  | indent 4 }}
spec:
  replicas: {{ .Values.app.api.replicaCount }}
  selector:
    matchLabels:
{{ include "fairy-music-api.selectorLabels" .  | indent 6 }}
  template:
    metadata:
      namespace: "{{ .Release.Namespace }}"
      name:  {{ include "fairy-music.name" . }}-api
      labels:
{{ include "fairy-music-api.selectorLabels" .  | indent 8 }}
{{ include "fairy-music.labels" .  | indent 8 }}
    spec:
      containers:
        - name:  {{ include "fairy-music.name" . }}-api
          image: "{{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}"
          resources:
            limits:
              cpu: "{{ .Values.app.api.resources.cpu }}"
              memory: "{{ .Values.app.api.resources.memory }}"
            requests:
              cpu: "{{ .Values.app.api.resources.cpu }}"
              memory: "{{ .Values.app.api.resources.memory }}"
          ports:
            - containerPort: {{ .Values.app.api.port }}
              protocol: "TCP"
          volumeMounts:
          - name: node-logs
            mountPath: /var/log/fairy-music
          env:
{{- toYaml .Values.env | nindent 10 }}
      restartPolicy: "Always"
      volumes:
      - name: node-logs
        hostPath:
          path: /var/log/fairy-music
          type: "DirectoryOrCreate"

---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "fairy-music.name" . }}-api-service
  labels:
{{ include "fairy-music.labels" .  | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      port: {{ .Values.app.api.port }}
      targetPort: {{ .Values.app.api.port }}
  sessionAffinity: "ClientIP"
  selector:
{{ include "fairy-music-api.selectorLabels" .  | indent 4 }}

