app:
  api:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-api
      tag: 1.0.0
    resources:
      cpu: "2"
      memory: "1024Mi"
    port: 18081

  ui:
    replicaCount: 1
    image:
      repository: striveonger/fairy-music-ui
      tag: 1.0.0
    resources:
      cpu: "2"
      memory: "256Mi"
    port: 80
    host: "music.striveonger.com"
  ingress:
    enabled: true
    path: /fm

env:
  - name: LOG_LEVEL
    value: info